package com.fpetrola.z80.instructions;

import com.fpetrola.z80.instructions.impl.Adc;
import com.fpetrola.z80.instructions.impl.Adc16;
import com.fpetrola.z80.instructions.impl.Add;
import com.fpetrola.z80.instructions.impl.Add16;
import com.fpetrola.z80.instructions.impl.And;
import com.fpetrola.z80.instructions.impl.BIT;
import com.fpetrola.z80.instructions.impl.CCF;
import com.fpetrola.z80.instructions.impl.CPL;
import com.fpetrola.z80.instructions.impl.Cp;
import com.fpetrola.z80.instructions.impl.Cpd;
import com.fpetrola.z80.instructions.impl.Cpi;
import com.fpetrola.z80.instructions.impl.DAA;
import com.fpetrola.z80.instructions.impl.Dec;
import com.fpetrola.z80.instructions.impl.In;
import com.fpetrola.z80.instructions.impl.Inc;
import com.fpetrola.z80.instructions.impl.Ini;
import com.fpetrola.z80.instructions.impl.LdAI;
import com.fpetrola.z80.instructions.impl.LdAR;
import com.fpetrola.z80.instructions.impl.Ldi;
import com.fpetrola.z80.instructions.impl.Neg;
import com.fpetrola.z80.instructions.impl.Or;
import com.fpetrola.z80.instructions.impl.Outi;
import com.fpetrola.z80.instructions.impl.RL;
import com.fpetrola.z80.instructions.impl.RLA;
import com.fpetrola.z80.instructions.impl.RLC;
import com.fpetrola.z80.instructions.impl.RLCA;
import com.fpetrola.z80.instructions.impl.RLD;
import com.fpetrola.z80.instructions.impl.RR;
import com.fpetrola.z80.instructions.impl.RRA;
import com.fpetrola.z80.instructions.impl.RRC;
import com.fpetrola.z80.instructions.impl.RRCA;
import com.fpetrola.z80.instructions.impl.RRD;
import com.fpetrola.z80.instructions.impl.SCF;
import com.fpetrola.z80.instructions.impl.SLA;
import com.fpetrola.z80.instructions.impl.SLL;
import com.fpetrola.z80.instructions.impl.SRA;
import com.fpetrola.z80.instructions.impl.SRL;
import com.fpetrola.z80.instructions.impl.Sbc;
import com.fpetrola.z80.instructions.impl.Sbc16;
import com.fpetrola.z80.instructions.impl.Sub;
import com.fpetrola.z80.instructions.impl.Xor;

public class Main1 {
  public static void main(String[] args) {
    RLA.RLAAluOperation rLAAluOperation = new RLA.RLAAluOperation();
    RRA.RRAAluOperation rRAAluOperation = new RRA.RRAAluOperation();
    RLCA.RlcaTableAluOperation rlcaTableAluOperation = new RLCA.RlcaTableAluOperation();
    RRCA.RRCAAluOperation rRCAAluOperation = new RRCA.RRCAAluOperation();
    RLC.RlcTable1AluOperation rlcTable1AluOperation = new RLC.RlcTable1AluOperation();
    RRC.RRCAluOperation rRCAluOperation = new RRC.RRCAluOperation();
    RL.RlTableAluOperation rlTableAluOperation = new RL.RlTableAluOperation();
    RR.RrTableAluOperation rrTableAluOperation = new RR.RrTableAluOperation();
    SLA.SlaTableAluOperation slaTableAluOperation = new SLA.SlaTableAluOperation();
    SRA.SRAAluOperation sRAAluOperation = new SRA.SRAAluOperation();
    SRL.SrlTableAluOperation srlTableAluOperation = new SRL.SrlTableAluOperation();
    SLL.SLLAluOperation sLLAluOperation = new SLL.SLLAluOperation();
    RLD.RldTableAluOperation rldTableAluOperation = new RLD.RldTableAluOperation();
    RRD.RrdTableAluOperation rrdTableAluOperation = new RRD.RrdTableAluOperation();
    Add.Add8TableAluOperation add8TableAluOperation = new Add.Add8TableAluOperation();
    Adc.Adc8TableAluOperation adc8TableAluOperation = new Adc.Adc8TableAluOperation();
    Sub.Sub8TableAluOperation sub8TableAluOperation = new Sub.Sub8TableAluOperation();
    Sbc.Sbc8TableAluOperation sbc8TableAluOperation = new Sbc.Sbc8TableAluOperation();
    And.AndTableAluOperation andTableAluOperation = new And.AndTableAluOperation();
    Xor.XorTableAluOperation xorTableAluOperation = new Xor.XorTableAluOperation();
    Or.OrTableAluOperation orTableAluOperation = new Or.OrTableAluOperation();
    Cp.CpTableAluOperation cpTableAluOperation = new Cp.CpTableAluOperation();
    Inc.Inc8TableAluOperation inc8TableAluOperation = new Inc.Inc8TableAluOperation();
    Dec.Dec8TableAluOperation dec8TableAluOperation = new Dec.Dec8TableAluOperation();
    DAA.DaaTableAluOperation daaTableAluOperation = new DAA.DaaTableAluOperation();
    CPL.CplTableAluOperation cplTableAluOperation = new CPL.CplTableAluOperation();
    SCF.ScfTableAluOperation scfTableAluOperation = new SCF.ScfTableAluOperation();
    CCF.CcfTableAluOperation ccfTableAluOperation = new CCF.CcfTableAluOperation();
    BIT.BitAluOperation bitAluOperation = new BIT.BitAluOperation();
    Ini.IniTableAluOperation iniTableAluOperation = new Ini.IniTableAluOperation();
    Ldi.LdiTableAluOperation ldiTableAluOperation = new Ldi.LdiTableAluOperation();
    Cpi.CpiTableAluOperation cpiTableAluOperation = new Cpi.CpiTableAluOperation();
    LdAI.LdaiTableAluOperation ldaiTableAluOperation = new LdAI.LdaiTableAluOperation();
    LdAR.LdarTableAluOperation ldarTableAluOperation = new LdAR.LdarTableAluOperation();
    Add16.Add16TableAluOperation add16TableAluOperation = new Add16.Add16TableAluOperation();
    Adc16.Adc16TableAluOperation adc16TableAluOperation = new Adc16.Adc16TableAluOperation();
    Sbc16.Sbc16TableAluOperation sbc16TableAluOperation = new Sbc16.Sbc16TableAluOperation();
    Cpd.CpdTableAluOperation cpdTableAluOperation = new Cpd.CpdTableAluOperation();
    In.InAluOperation inAluOperation = new In.InAluOperation();
    Outi.OutiTableAluOperation outiTableAluOperation = new Outi.OutiTableAluOperation();
    Neg.NegTableAluOperation negTableAluOperation = new Neg.NegTableAluOperation();
  }
}
