package com.fpetrola.oozx;// settings.java: Handling configuration settings
// Copyright (c) 2001-2003 Philip Kendall
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
// Author contact information:
// E-mail: philip-fuse@shadowmagic.org.uk

// This file is autogenerated from settings.dat by settings-header.pl.
// Do not edit unless you know what will happen!

// Assuming ported dependencies:
// - Libspectrum
// - StartupManager, StartupManagerModule
// - Other necessary classes for file handling (e.g., Utils)

import com.fpetrola.oozx.fuse.modules.Joystick;

public class Settings {

  public static void setString(String startMachine, String id) {

  }

  public static class SettingsInfo {
    public boolean accelerateLoader;
    public boolean aspectHint;
    public boolean autoLoad;
    public boolean autosaveSettings;
    public boolean beta128;
    public boolean beta12848Boot;
    public String betadiskFile;
    public boolean bwTv;
    public boolean competitionCode;
    public boolean competitionMode;
    public boolean confirmActions;
    public boolean covox;
    public String dckFile;
    public String debuggerCommand;
    public boolean detectLoader;
    public boolean didaktik80;
    public String didaktik80diskFile;
    public boolean disciple;
    public String disciplediskFile;
    public boolean diskAskMerge;
    public String diskTryMerge;
    public boolean divideEnabled;
    public String divideMasterFile;
    public String divideSlaveFile;
    public boolean divideWp;
    public boolean divmmcEnabled;
    public String divmmcFile;
    public boolean divmmcWp;
    public boolean doublescanMode;
    public int drive40MaxTrack;
    public int drive80MaxTrack;
    public String driveBeta128aType;
    public String driveBeta128bType;
    public String driveBeta128cType;
    public String driveBeta128dType;
    public String driveDidaktik80aType;
    public String driveDidaktik80bType;
    public String driveDisciple1Type;
    public String driveDisciple2Type;
    public String driveOpus1Type;
    public String driveOpus2Type;
    public String drivePlus3aType;
    public String drivePlus3bType;
    public String drivePlusd1Type;
    public String drivePlusd2Type;
    public boolean embedSnapshot;
    public int emulationSpeed;
    public boolean fastload;
    public int fbMode;
    public int frameRate;
    public boolean fullScreen;
    public boolean fuller;
    public String if2File;
    public boolean interface1;
    public boolean interface2;
    public boolean issue2;
    public boolean joyKempston;
    public boolean joyPrompt;
    public String joystick1;
    public int joystick1Fire1;
    public int joystick1Fire10;
    public int joystick1Fire11;
    public int joystick1Fire12;
    public int joystick1Fire13;
    public int joystick1Fire14;
    public int joystick1Fire15;
    public int joystick1Fire2;
    public int joystick1Fire3;
    public int joystick1Fire4;
    public int joystick1Fire5;
    public int joystick1Fire6;
    public int joystick1Fire7;
    public int joystick1Fire8;
    public int joystick1Fire9;
    public Joystick.JoystickType joystick1Output;
    public String joystick2;
    public int joystick2Fire1;
    public int joystick2Fire10;
    public int joystick2Fire11;
    public int joystick2Fire12;
    public int joystick2Fire13;
    public int joystick2Fire14;
    public int joystick2Fire15;
    public int joystick2Fire2;
    public int joystick2Fire3;
    public int joystick2Fire4;
    public int joystick2Fire5;
    public int joystick2Fire6;
    public int joystick2Fire7;
    public int joystick2Fire8;
    public int joystick2Fire9;
    public Joystick.JoystickType joystick2Output;
    public int joystickKeyboardDown;
    public int joystickKeyboardFire;
    public int joystickKeyboardLeft;
    public Joystick.JoystickType joystickKeyboardOutput;
    public int joystickKeyboardRight;
    public int joystickKeyboardUp;
    public boolean kempstonMouse;
    public boolean keyboardArrowsShifted;
    public boolean lateTimings;
    public String mdrFile;
    public String mdrFile2;
    public String mdrFile3;
    public String mdrFile4;
    public String mdrFile5;
    public String mdrFile6;
    public String mdrFile7;
    public String mdrFile8;
    public int mdrLen;
    public int mdrRandomLen;
    public boolean melodik;
    public boolean mouseSwapButtons;
    public String movieCompr;
    public String movieStart;
    public boolean movieStopAfterRzx;
    public boolean multiface1;
    public boolean multiface128;
    public boolean multiface1Stealth;
    public boolean multiface3;
    public boolean opus;
    public String opusdiskFile;
    public boolean palTv2x;
    public String phantomTypistMode;
    public String playbackFile;
    public boolean plus3DetectSpeedlock;
    public String plus3diskFile;
    public boolean plusd;
    public String plusddiskFile;
    public boolean printer;
    public String printerGraphicsFilename;
    public String printerTextFilename;
    public boolean rawSNet;
    public String recordFile;
    public boolean recreatedSpectrum;
    public String rom1280;
    public String rom1281;
    public String rom16;
    public String rom48;
    public String romBeta128;
    public String romDidaktik80;
    public String romDisciple;
    public String romInterface1;
    public String romMultiface1;
    public String romMultiface128;
    public String romMultiface3;
    public String romOpus;
    public String romPentagon10240;
    public String romPentagon10241;
    public String romPentagon10242;
    public String romPentagon10243;
    public String romPentagon5120;
    public String romPentagon5121;
    public String romPentagon5122;
    public String romPentagon5123;
    public String romPentagon0;
    public String romPentagon1;
    public String romPentagon2;
    public String romPlus20;
    public String romPlus21;
    public String romPlus2a0;
    public String romPlus2a1;
    public String romPlus2a2;
    public String romPlus2a3;
    public String romPlus30;
    public String romPlus31;
    public String romPlus32;
    public String romPlus33;
    public String romPlus3e0;
    public String romPlus3e1;
    public String romPlus3e2;
    public String romPlus3e3;
    public String romPlusd;
    public String romScorpion0;
    public String romScorpion1;
    public String romScorpion2;
    public String romScorpion3;
    public String romSpecSe0;
    public String romSpecSe1;
    public String romSpeccyboot;
    public String romTc2048;
    public String romTc20680;
    public String romTc20681;
    public String romTs20680;
    public String romTs20681;
    public String romTtx2000s;
    public String romUsource;
    public boolean rs232Handshake;
    public String rs232Rx;
    public String rs232Tx;
    public boolean rzxAutosaves;
    public boolean rzxCompression;
    public String sdlFullscreenMode;
    public boolean simpleideActive;
    public String simpleideMasterFile;
    public String simpleideSlaveFile;
    public boolean sltTraps;
    public String snapshot;
    public String snet;
    public boolean sound;
    public String soundDevice;
    public boolean soundForce8bit;
    public int soundFreq;
    public boolean soundLoad;
    public String speakerType;
    public boolean speccyboot;
    public String speccybootTap;
    public boolean specdrum;
    public boolean spectranet;
    public boolean spectranetDisable;
    public String startMachine;
    public String startScalerMode;
    public boolean statusbar;
    public String stereoAy;
    public boolean strictAspectHint;
    public String svgaModes;
    public String tapeFile;
    public boolean tapeTraps;
    public String teletextAddr1;
    public String teletextAddr2;
    public String teletextAddr3;
    public String teletextAddr4;
    public int teletextPort1;
    public int teletextPort2;
    public int teletextPort3;
    public int teletextPort4;
    public boolean ttx2000s;
    public boolean unittests;
    public boolean usource;
    public int volumeAy;
    public int volumeBeeper;
    public int volumeCovox;
    public int volumeSpecdrum;
    public boolean writableRoms;
    public boolean z80IsCmos;
    public boolean zxataspActive;
    public String zxataspMasterFile;
    public String zxataspSlaveFile;
    public boolean zxataspUpload;
    public boolean zxataspWp;
    public boolean zxcfActive;
    public String zxcfPriFile;
    public boolean zxcfUpload;
    public boolean zxmmcEnabled;
    public String zxmmcFile;
    public boolean zxprinter;

    public boolean showHelp;
    public boolean showVersion;
  }

  public static SettingsInfo current = new SettingsInfo();
  public static SettingsInfo defaults = new SettingsInfo();

  public static final int SETTINGS_ROM_COUNT = 30;

  public static int init(String[] args) {
    return 0;
  }

  public static void defaults(SettingsInfo settings) {
    throw new UnsupportedOperationException("settings_defaults not implemented");
  }

  public static void copy(SettingsInfo dest, SettingsInfo src) {
    throw new UnsupportedOperationException("settings_copy not implemented");
  }

  public static String[] getRomSetting(SettingsInfo settings, int which, boolean isPeripheral) {
    throw new UnsupportedOperationException("settings_get_rom_setting not implemented");
  }

  public static void setString(String[] stringSetting, String value) {
    throw new UnsupportedOperationException("settings_set_string not implemented");
  }

  public static int free(SettingsInfo settings) {
    throw new UnsupportedOperationException("settings_free not implemented");
  }

  public static int writeConfig(SettingsInfo settings) {
    throw new UnsupportedOperationException("settings_write_config not implemented");
  }

}